from __future__ import annotations

import random
import zlib
from dataclasses import dataclass
from typing import Any, Iterable, Optional

import chess

from halluworld.serializer import Serializer


@dataclass(frozen=True)
class FenDisplayConfig:
    """How to render the FEN line when ``include_fen`` is true (red-team / stress).

    ``mode``:
      - ``truth`` — show the real position FEN.
      - ``flip_turn`` — same piece placement; toggle the active-color field only.
      - ``transpose`` — swap two non-king pieces on the board (still a parseable FEN).
      - ``startpos`` — always show the standard starting FEN string.
      - ``override`` — show ``override_fen`` when set, else fall back to truth.
    ``seed`` — stabilizes ``transpose`` pair selection (XOR with a CRC32 of the true FEN).
    """

    mode: str = "truth"
    override_fen: Optional[str] = None
    seed: int = 0


_active_fen_display: Optional[FenDisplayConfig] = None


def configure_observation_fen_display(cfg: Optional[FenDisplayConfig]) -> None:
    """Set global FEN-line mutation for :func:`render_history` / :func:`render_full` when no explicit cfg is passed.

    Pass ``None`` to clear (revert to truth-only default).
    """
    global _active_fen_display
    _active_fen_display = cfg


def effective_fen_display(explicit: Optional[FenDisplayConfig]) -> FenDisplayConfig:
    if explicit is not None:
        return explicit
    if _active_fen_display is not None:
        return _active_fen_display
    return FenDisplayConfig()


def _fen_toggle_active_color(fen: str) -> str:
    parts = fen.split()
    if len(parts) < 2:
        return fen
    ac = parts[1].lower()
    parts[1] = "b" if ac == "w" else "w"
    return " ".join(parts)


def derive_display_fen(true_fen: str, cfg: FenDisplayConfig) -> str:
    """Return the FEN string to print in observations (may differ from *true_fen*)."""
    mode = (cfg.mode or "truth").strip().lower()
    if mode in ("truth", "none", ""):
        return true_fen
    if mode == "flip_turn":
        return _fen_toggle_active_color(true_fen)
    if mode == "startpos":
        return chess.STARTING_FEN
    if mode in ("override", "replace"):
        if cfg.override_fen and cfg.override_fen.strip():
            return cfg.override_fen.strip()
        return true_fen
    if mode in ("transpose", "swap", "swap_two"):
        base = chess.Board(true_fen)
        occ = [sq for sq in chess.SQUARES if base.piece_at(sq) is not None]
        if len(occ) < 2:
            return true_fen
        # zlib.crc32, not hash(): str hashes are salted per process
        # (PYTHONHASHSEED), which made the swapped pair differ on every run.
        # Banks frozen before this fix (v0.2's chess_fen_transpose) keep their
        # original swaps; they cannot be regenerated byte-for-byte.
        rng = random.Random((cfg.seed ^ zlib.crc32(true_fen.encode("utf-8"))) & 0xFFFFFFFF)
        for _ in range(48):
            b2 = chess.Board(true_fen)
            a, c = rng.sample(occ, 2)
            pa, pc = b2.piece_at(a), b2.piece_at(c)
            if pa is None or pc is None:
                continue
            if pa.piece_type == chess.KING or pc.piece_type == chess.KING:
                continue
            b2.set_piece_at(a, pc)
            b2.set_piece_at(c, pa)
            out = b2.fen()
            if out != true_fen:
                return out
        return true_fen
    return true_fen


_PIECE_NAMES = {
    "P": "white pawn",
    "N": "white knight",
    "B": "white bishop",
    "R": "white rook",
    "Q": "white queen",
    "K": "white king",
    "p": "black pawn",
    "n": "black knight",
    "b": "black bishop",
    "r": "black rook",
    "q": "black queen",
    "k": "black king",
}


def board_to_grid_text(
    board: chess.Board,
    mask: Optional[Iterable[int]] = None,
    mask_char: str = "?",
) -> str:
    """Render an 8x8 board grid with explicit coordinates.

    If ``mask`` is supplied, those squares are rendered as ``mask_char`` instead
    of their actual contents (used by belief / uncertainty probes).
    """
    mask_set = set(mask) if mask else set()
    lines = []
    for rank in range(8, 0, -1):
        row = []
        for file_idx in range(8):
            square = chess.square(file_idx, rank - 1)
            if square in mask_set:
                row.append(mask_char)
            else:
                piece = board.piece_at(square)
                row.append(piece.symbol() if piece else ".")
        lines.append(f"{rank} {' '.join(row)}")
    lines.append("  a b c d e f g h")
    return "\n".join(lines)


def render_full(
    board: chess.Board,
    *,
    include_legal_moves: bool = True,
    max_legal_moves: int = 30,
    mask: Optional[Iterable[int]] = None,
    include_fen: bool = True,
    fen_display: Optional[FenDisplayConfig] = None,
) -> str:
    """Render the standard observation: header + grid + side + FEN + legal moves.

    Used by both :class:`ChessSerializer` and the masked-view belief probes.
    Pass ``mask`` to hide specific squares; when the board is masked we drop
    the FEN line by default so the model can't bypass the mask.
    """
    mask_set = set(mask) if mask else set()
    side = "white" if board.turn == chess.WHITE else "black"

    lines = [
        "You are evaluating a chess position.",
        "Coordinates follow standard chess notation: files a-h, ranks 1-8.",
    ]
    if getattr(board, "halluworld_variant", None) == "old_bishop":
        lines.append(
            "Variant note: bishops slide diagonally but at most two squares along one direction "
            "per bishop move; queens follow normal sliding rules."
        )
    if getattr(board, "halluworld_variant", None) == "atomic":
        lines.append(
            "Variant note: Lichess atomic chess — captures explode adjacent non-pawn pieces; "
            "special king connectivity and castling rules apply."
        )
    if mask_set:
        lines.append(
            f"Board ('.' means empty, '?' means hidden — contents unknown):"
        )
    else:
        lines.append("Board ('.' means empty):")
    lines.append(board_to_grid_text(board, mask=mask_set))
    lines.append(f"Side to move: {side}")
    if include_fen and not mask_set:
        cfg = effective_fen_display(fen_display)
        lines.append(f"FEN: {derive_display_fen(board.fen(), cfg)}")
    if include_legal_moves and not mask_set:
        legal = sorted(move.uci() for move in board.legal_moves)
        preview = legal[:max_legal_moves]
        suffix = "" if len(preview) == len(legal) else f" ... (+{len(legal) - len(preview)} more)"
        lines.append(f"Legal moves (UCI): {', '.join(preview)}{suffix}")
    return "\n".join(lines)


def render_history(
    start_fen: str,
    moves_uci: list[str],
    *,
    include_san: bool = True,
    fen_display: Optional[FenDisplayConfig] = None,
    companion_board: bool = False,
) -> str:
    """Render a move-history observation, optionally without the history-only preamble.

    By default, renders a standalone history block (starting FEN + moves, no grid)
    for memory probes that hide ``V``.

    When ``companion_board`` is True, omit the "history alone" framing, the starting
    FEN line, and trailing side-to-move — the caller shows a board + FEN from
    :func:`render_full` / :class:`ChessSerializer` above this text, so those lines
    would be redundant or misleading (e.g. under transposed FEN display).
    """
    cfg = effective_fen_display(fen_display)
    shown_start = derive_display_fen(start_fen, cfg)
    preamble = [
        "You are evaluating a chess game by its move history alone.",
        "No board grid is shown; you must track the position from the moves.",
        f"Starting FEN: {shown_start}",
    ]

    move_lines: list[str] = []

    if not moves_uci:
        if companion_board:
            return ""
        lines = preamble + ["Moves played: (none yet)"]
        try:
            board = chess.Board(start_fen)
            side = "white" if board.turn == chess.WHITE else "black"
            lines.append(f"Side to move: {side}")
        except Exception:
            pass
        return "\n".join(lines)

    if include_san:
        try:
            board = chess.Board(start_fen)
            san_pairs = []
            for uci in moves_uci:
                mv = chess.Move.from_uci(uci)
                san = board.san(mv)
                san_pairs.append(f"{uci} ({san})")
                board.push(mv)
            move_lines.append("Moves played (UCI with SAN):")
            move_lines.append("  " + ", ".join(san_pairs))
            if not companion_board:
                side = "white" if board.turn == chess.WHITE else "black"
                move_lines.append(f"Side to move: {side}")
        except Exception:
            move_lines.append(f"Moves played (UCI): {' '.join(moves_uci)}")
    else:
        move_lines.append(f"Moves played (UCI): {' '.join(moves_uci)}")

    if companion_board:
        return "\n".join(move_lines)
    return "\n".join(preamble + move_lines)


def render_atomic_san_history_observation(
    env: Any,
    *,
    include_legal_moves: bool,
    max_legal_moves: int,
    include_fen: bool,
    fen_display: Optional[FenDisplayConfig] = None,
) -> str:
    """Observation text: episode root FEN + SAN list to current position (no grid)."""
    from halluworld.tracks.chess.rules.atomic_board import AtomicBoard

    board = env.board
    root = getattr(env, "_episode_root_fen", None)
    uci_hist = getattr(env, "_episode_moves_uci", None)
    if root is None or uci_hist is None or not isinstance(board, AtomicBoard):
        return render_full(
            board,
            include_legal_moves=include_legal_moves,
            max_legal_moves=max_legal_moves,
            include_fen=include_fen,
            fen_display=fen_display,
        )

    replay = AtomicBoard(root)
    sans: list[str] = []
    for u in uci_hist:
        mv = chess.Move.from_uci(u)
        if mv not in replay.legal_moves:
            return render_full(
                board,
                include_legal_moves=include_legal_moves,
                max_legal_moves=max_legal_moves,
                include_fen=include_fen,
                fen_display=fen_display,
            )
        sans.append(replay.san(mv))
        replay.push(mv)
    if replay.fen() != board.fen():
        return render_full(
            board,
            include_legal_moves=include_legal_moves,
            max_legal_moves=max_legal_moves,
            include_fen=include_fen,
            fen_display=fen_display,
        )

    cfg = effective_fen_display(fen_display)
    side = "white" if board.turn == chess.WHITE else "black"
    lines = [
        "You are evaluating a Lichess **atomic** chess position from the move list alone (no board grid).",
        "Coordinates are files a-h, ranks 1-8.",
        f"Starting FEN (beginning of this episode, before warm-up plies): {derive_display_fen(root, cfg)}",
        "Moves played from that FEN to reach the current position (SAN, in order): "
        + (" ".join(sans) if sans else "(none)"),
        f"Side to move: {side}",
    ]
    if include_fen:
        lines.append(f"Current FEN: {derive_display_fen(board.fen(), cfg)}")
    if include_legal_moves:
        legal = sorted(m.uci() for m in board.legal_moves)
        preview = legal[:max_legal_moves]
        suffix = "" if len(preview) == len(legal) else f" ... (+{len(legal) - len(preview)} more)"
        lines.append(f"Legal moves (UCI): {', '.join(preview)}{suffix}")
    return "\n".join(lines)


class ChessSerializer(Serializer):
    """Serializes a chess board into a structured prompt-ready text block."""

    def __init__(
        self,
        include_legal_moves: bool = True,
        max_legal_moves: int = 30,
        include_fen: bool = True,
        observation_mode: str = "grid",
        fen_display: Optional[FenDisplayConfig] = None,
    ):
        self.include_legal_moves = include_legal_moves
        self.max_legal_moves = max_legal_moves
        self.include_fen = include_fen
        self.observation_mode = observation_mode
        self.fen_display = fen_display

    def serialize(self, env: Any) -> str:
        if self.observation_mode == "san_history" and getattr(env.board, "halluworld_variant", None) == "atomic":
            return render_atomic_san_history_observation(
                env,
                include_legal_moves=self.include_legal_moves,
                max_legal_moves=self.max_legal_moves,
                include_fen=self.include_fen,
                fen_display=self.fen_display,
            )
        return render_full(
            env.board,
            include_legal_moves=self.include_legal_moves,
            max_legal_moves=self.max_legal_moves,
            include_fen=self.include_fen,
            fen_display=self.fen_display,
        )


def piece_name(piece: chess.Piece) -> str:
    return _PIECE_NAMES[piece.symbol()]


def parse_piece_name(text: str) -> Optional[str]:
    """Extract a canonical piece name (e.g. 'white knight') from free-form text.

    Returns ``"empty"`` if the text indicates emptiness, or ``None`` if no
    canonical piece label can be found.
    """
    t = text.strip().lower()
    if not t:
        return None
    for canonical in _PIECE_NAMES.values():
        if canonical in t:
            return canonical
    if "empty" in t or "nothing" in t or t in {".", "none", "no piece"}:
        return "empty"
    return None
