#!/usr/bin/env bash
#
# Generate a held-out question bank (v0.2 by default).
#
#     scripts/build_v02_bank.sh CONFIG.env
#
# The v0.2 configs and the authored grid source are NOT in this repository:
# they carry the held-out seeds and items. They are in the gated
# DegenAI-Labs/HalluWorld dataset; keep them outside the checkout and pass the
# path (the dataset's v0.2/README.md has the exact steps):
#
#     hf download DegenAI-Labs/HalluWorld --repo-type dataset --local-dir ../halluworld-hf --include "v0.2/*"
#     scripts/build_v02_bank.sh ../halluworld-hf/v0.2/configs/chess.env
#
# Reads a config file of generation variables, regenerates the chess question
# set under StubLM (no API calls, no cost), freezes it into the v0.2 bank, and
# checks it for contamination against v0.1.
#
# Run it from the repository root.
#
# ---------------------------------------------------------------------------
# Track coverage
# ---------------------------------------------------------------------------
# chess     generated here, fully config-driven.
# grid      AUTHORED, never generated from a seed: 434 of v0.1 grid's 443
#           records are FixedProbe literals hardcoded in perception.py and the
#           other 9 freeze as class+kwargs recipes, so rebuilding at any seed
#           gives a byte-identical bank. A new grid set therefore arrives as a
#           curated .jsonl in the shared record schema. Point GRID_SOURCE at it
#           and add grid to TRACKS:
#             TRACKS="grid chess" GRID_SOURCE=path/to/questions.jsonl \
#               scripts/build_v02_bank.sh
# terminal  generated by the terminal-bench runtime injectors, not here. Its
#           extracted probes ship as v0.2/raw/terminal in DegenAI-Labs/HalluWorld;
#           build with build_question_bank.py --tracks terminal --terminal-source
#           <that folder> --terminal-namespace extracted_llm_probes_heldout_20260908.
# innav     derives from grid's probe definitions; no v0.2 set yet.
#
set -euo pipefail

if [[ $# -lt 1 ]]; then
  echo "usage: scripts/build_v02_bank.sh CONFIG.env   (see the header of this script)" >&2
  exit 2
fi
# Resolve paths given relative to the caller before moving to the repo root.
CONFIG="$(realpath -m "$1")"
if [[ -n "${GRID_SOURCE:-}" ]]; then GRID_SOURCE="$(realpath -m "$GRID_SOURCE")"; fi

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"

BANK_VERSION="${BANK_VERSION:-v0.2}"
TRACKS="${TRACKS:-chess}"
# Which chess condition this config freezes: "chess" for No-FEN, or
# "chess_fen_transpose" (etc.) to add another FEN condition to the same bank.
CHESS_BANK_KEY="${CHESS_BANK_KEY:-chess}"

if [[ ! -f "$CONFIG" ]]; then
  echo "error: config file not found: $CONFIG" >&2
  exit 1
fi

# ---------------------------------------------------------------------------
# Load config
# ---------------------------------------------------------------------------
# Only KEY=VALUE lines are honoured; anything else in the file is a hard error
# rather than something bash would silently execute.
if grep -vE '^[[:space:]]*(#|$)' "$CONFIG" | grep -qvE '^[A-Z_][A-Z0-9_]*='; then
  echo "error: $CONFIG has lines that are not KEY=VALUE:" >&2
  grep -vE '^[[:space:]]*(#|$)' "$CONFIG" | grep -vE '^[A-Z_][A-Z0-9_]*=' >&2
  exit 1
fi

set -a
# shellcheck disable=SC1090
source "$CONFIG"
set +a

: "${QUESTION_SET_NAME:?set QUESTION_SET_NAME in $CONFIG}"
: "${BENCHMARK_SEED:?set BENCHMARK_SEED in $CONFIG}"
: "${N_EPISODES:?set N_EPISODES in $CONFIG}"

# v0.1 was generated at seed 42. Reusing it reproduces v0.1's positions, which
# would defeat the entire point of a held-out set.
if [[ "$BENCHMARK_SEED" == "42" ]]; then
  echo "error: BENCHMARK_SEED=42 is the v0.1 seed; a held-out set needs a different one." >&2
  exit 1
fi

# BENCHMARK_SEED varies the probes asked about a position; with USE_LICHESS=1 it
# is LICHESS_SEED that varies which positions are drawn. Leaving that at v0.1's
# 42 over v0.1's rating band silently reuses v0.1's exact 200 puzzles.
if [[ "${USE_LICHESS:-0}" == "1" ]]; then
  if [[ "${LICHESS_SEED:-42}" == "42" ]] \
     && [[ "${LICHESS_MIN_RATING:-1200}" == "1200" ]] \
     && [[ "${LICHESS_MAX_RATING:-2200}" == "2200" ]]; then
    echo "error: USE_LICHESS=1 with v0.1's puzzle draw (LICHESS_SEED=42, rating" >&2
    echo "       1200-2200) returns v0.1's exact 200 positions. Change LICHESS_SEED," >&2
    echo "       and prefer a rating band disjoint from 1200-2200." >&2
    exit 1
  fi
fi

# Grid is authored, not generated: it arrives as a curated .jsonl in the shared
# record schema. Point GRID_SOURCE at it and add grid to TRACKS.
GRID_SOURCE="${GRID_SOURCE:-}"
if [[ " $TRACKS " == *" grid "* && -z "$GRID_SOURCE" ]]; then
  echo "error: TRACKS includes grid, so GRID_SOURCE must point at the curated" >&2
  echo "       grid questions .jsonl (grid cannot be generated from a seed)." >&2
  exit 1
fi
if [[ -n "$GRID_SOURCE" && ! -f "$GRID_SOURCE" ]]; then
  echo "error: GRID_SOURCE not found: $GRID_SOURCE" >&2
  exit 1
fi

STAGE_ROOT="${HALLUWORLD_RESULTS_ROOT:-$REPO_ROOT/build/v02}"
EXPORT_DIR="$STAGE_ROOT/results/chess/question_sets/$QUESTION_SET_NAME"

echo "=============================================================="
echo "  HalluWorld $BANK_VERSION question bank"
echo "=============================================================="
echo "config:        $CONFIG"
echo "tracks:        $TRACKS"
echo "seed:          $BENCHMARK_SEED"
echo "episodes:      $N_EPISODES"
echo "export dir:    $EXPORT_DIR"
echo

# ---------------------------------------------------------------------------
# 1. Regenerate the chess question set (StubLM: no API calls)
# ---------------------------------------------------------------------------
if [[ " $TRACKS " == *" chess "* ]]; then
  echo "[1/4] generating chess questions ..."
  HALLUWORLD_RESULTS_ROOT="$STAGE_ROOT" \
    python3 -m halluworld.tracks.chess.question_set

  if [[ ! -f "$EXPORT_DIR/questions.jsonl" ]]; then
    echo "error: expected export at $EXPORT_DIR/questions.jsonl" >&2
    exit 1
  fi
  echo "      $(wc -l < "$EXPORT_DIR/questions.jsonl") questions exported"
else
  echo "[1/4] chess not in TRACKS; skipping generation"
fi

# ---------------------------------------------------------------------------
# 2. Record the config this set was generated under
# ---------------------------------------------------------------------------
# build_question_bank.py folds this into each record's provenance, so "how v0.2
# was made" stays public and reproducible even while the instances stay private.
echo "[2/4] recording generation config ..."
if [[ " $TRACKS " == *" chess "* ]]; then
CONFIG_PATH="$CONFIG" EXPORT_DIR="$EXPORT_DIR" python3 - <<'PY'
import json, os, re, subprocess

config_path, export_dir = os.environ["CONFIG_PATH"], os.environ["EXPORT_DIR"]
env = {}
for line in open(config_path, encoding="utf-8"):
    line = line.strip()
    if line and not line.startswith("#") and re.match(r"^[A-Z_][A-Z0-9_]*=", line):
        key, _, value = line.partition("=")
        env[key] = value

try:
    sha = subprocess.run(["git", "rev-parse", "HEAD"], capture_output=True,
                         text=True, check=True).stdout.strip()
except Exception:
    sha = ""

json.dump(
    {
        "exported": __import__("datetime").datetime.now(
            __import__("datetime").timezone.utc).strftime("%Y-%m-%d"),
        "config_file": config_path,
        "git_sha": sha,
        "env": env,
    },
    open(os.path.join(export_dir, "generation_config.json"), "w"),
    indent=2, sort_keys=True,
)
print("      wrote generation_config.json (%d knobs)" % len(env))
PY
else
  echo "      chess not in TRACKS; nothing to record"
fi

# ---------------------------------------------------------------------------
# 3. Freeze into the bank
# ---------------------------------------------------------------------------
echo "[3/4] freezing bank $BANK_VERSION ..."
# shellcheck disable=SC2086
BUILD_ARGS=(--version "$BANK_VERSION" --tracks $TRACKS --chess-source "$EXPORT_DIR" --chess-key "$CHESS_BANK_KEY")
if [[ -n "$GRID_SOURCE" ]]; then
  BUILD_ARGS+=(--grid-source "$GRID_SOURCE")
fi
python3 scripts/build_question_bank.py "${BUILD_ARGS[@]}" | sed 's/^/      /'

# ---------------------------------------------------------------------------
# 4. Contamination check against v0.1
# ---------------------------------------------------------------------------
echo "[4/4] checking for overlap with v0.1 ..."
BANK_VERSION="$BANK_VERSION" TRACKS="$TRACKS" CHESS_BANK_KEY="$CHESS_BANK_KEY" python3 - <<'PY'
import os, sys
sys.path.insert(0, ".")
from pathlib import Path
from halluworld.questions import read_bank

version, tracks = os.environ["BANK_VERSION"], os.environ["TRACKS"].split()
root = Path("halluworld/data/questions")
failed = False
for track in tracks:
    stem = os.environ["CHESS_BANK_KEY"] if track == "chess" else track
    new_path, old_path = root / version / f"{stem}.jsonl.gz", root / "v0.1" / f"{track}.jsonl.gz"
    if not old_path.exists():
        print(f"      {track}: no v0.1 bank to compare against")
        continue
    new, old = list(read_bank(new_path)), list(read_bank(old_path))

    by_question = {}
    for r in old:
        by_question.setdefault(r.question, []).append(r)

    # A leaked item is the same question asked about the same context. Sharing
    # question TEXT alone is not leakage for templated tracks: chess asks "Can
    # white legally capture the black knight on f6?" about thousands of
    # different boards, and the answer differs with the board.
    text_hits = [r for r in new if r.question in by_question]
    dupes = [r for r in text_hits
             if any(o.context == r.context for o in by_question[r.question])]
    shared_ids = {r.question_id for r in new} & {r.question_id for r in old}

    uniq = {r.question for r in new if r.question}
    pct = 100.0 * len(uniq & set(by_question)) / len(uniq) if uniq else 0.0
    print(f"      {track}: {len(new)} questions, {len(dupes)} duplicated items, "
          f"{len(shared_ids)} shared ids "
          f"({pct:.1f}% of unique texts recur, on different positions)")
    if dupes or shared_ids:
        failed = True

if failed:
    print("\nFAIL: the new bank repeats items from v0.1. It is not held out.")
    sys.exit(1)
PY

echo
echo "=============================================================="
echo "done. bank at halluworld/data/questions/$BANK_VERSION/"
echo
echo "Verify:  halluworld questions verify --version $BANK_VERSION"
echo "Stats:   halluworld questions stats  --version $BANK_VERSION"
echo "Run:     halluworld eval chess --provider openai --model MODEL \\"
echo "             --version $BANK_VERSION --out results/chess_$BANK_VERSION"
echo
echo "This bank is HELD OUT. halluworld/data/questions/v0.2/ is gitignored;"
echo "keep it out of the public repo and publish only its manifest checksums."
echo "=============================================================="
